### Merging

In [7]:
import pandas as pd 

employees = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104],
    'Name': ['Ali', 'Sara', 'Ahmed', 'Zara']
})

departments = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104],
    'Department': ['AI', 'Software', 'Network', 'AI']
})

df = employees.merge(departments, on = 'Emp_ID', how = 'inner')
df

   Emp_ID   Name Department
0     101    Ali         AI
1     102   Sara   Software
2     103  Ahmed    Network
3     104   Zara         AI

In [9]:
salary = pd.DataFrame({
    'Emp_ID':[101,102,103,104],
    'Salary':[60000,55000,50000,70000]
})

df = df.merge(salary, on = 'Emp_ID', how = 'inner')
df

   Emp_ID   Name Department  Salary
0     101    Ali         AI   60000
1     102   Sara   Software   55000
2     103  Ahmed    Network   50000
3     104   Zara         AI   70000

In [10]:
employees = pd.DataFrame({
    'Emp_ID':[101,102,103,104],
    'Name':['Ali','Sara','Ahmed','Zara']
})

salary = pd.DataFrame({
    'Emp_ID':[101,103],
    'Salary':[60000,50000]
})

print(employees.merge(salary, on = 'Emp_ID', how = 'inner'))
print(employees.merge(salary, on = 'Emp_ID', how = 'left'))

   Emp_ID   Name  Salary
0     101    Ali   60000
1     103  Ahmed   50000
   Emp_ID   Name   Salary
0     101    Ali  60000.0
1     102   Sara      NaN
2     103  Ahmed  50000.0
3     104   Zara      NaN

### Pivot Table

In [38]:
df = pd.DataFrame({
    'Department':['AI','AI','AI','Software','Software','Network'],
    'Gender':['M','F','M','F','M','F'],
    'Salary':[60000,65000,62000,50000,52000,47000]
})

df.pivot_table(index = 'Department', columns = 'Gender', values = 'Salary', aggfunc = 'mean')

Gender            F        M
Department
AI          65000.0  61000.0
Network     47000.0      NaN
Software    50000.0  52000.0

In [40]:
df.pivot_table(index = 'Department', values = 'Salary', aggfunc = 'sum')

            Salary
Department
AI          187000
Network      47000
Software    102000

In [ ]:
df.pivot_table(
    index='Department',
    values='Salary',
    aggfunc=['mean', 'max', 'min']
)

                    mean    max    min
                  Salary Salary Salary
Department
AI          62333.333333  65000  60000
Network     47000.000000  47000  47000
Software    51000.000000  52000  50000

### Melt

In [ ]:
df = pd.DataFrame({
    'Student':['Ali','Sara'],
    'Math':[90,80],
    'Physics':[85,95],
    'Chemistry':[88,91]
})

melted = df.melt(id_vars = 'Student', var_name = 'Subject', value_vars = ['Math', 'Physics', 'Chemistry'], value_name = 'Marks')

subject_order = ['Math', 'Physics', 'Chemistry']
melted['Subject'] = pd.Categorical(melted['Subject'], categories = subject_order, ordered = True)

melted = melted.sort_values(['Student', 'Subject'])
melted

  Student    Subject  Marks
0     Ali       Math     90
2     Ali    Physics     85
4     Ali  Chemistry     88
1    Sara       Math     80
3    Sara    Physics     95
5    Sara  Chemistry     91

In [82]:
melted.rename(columns = {'Subject': 'Course', 'Marks': 'Score'}, inplace = True)
melted

  Student     Course  Score
0     Ali       Math     90
2     Ali    Physics     85
4     Ali  Chemistry     88
1    Sara       Math     80
3    Sara    Physics     95
5    Sara  Chemistry     91

### Working with Real Datasets

In [ ]:
df = pd.DataFrame({
    'Name':['Ali',None,'Ahmed','Sara'],
    'Age':[20,21,None,22],
    'Department':['AI',None,'AI','Software']
})

print(df.isna().sum())
df['Name'] = df['Name'].fillna('Unknown')
df['Department'] = df['Department'].fillna('Not Assigned')
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

Name          1
Age           1
Department    1
dtype: int64

      Name   Age    Department
0      Ali  20.0            AI
1  Unknown  21.0  Not Assigned
2    Ahmed  21.0            AI
3     Sara  22.0      Software

In [ ]:
df = pd.DataFrame({
    'Name':['Ali','Ali','Sara','Ahmed','Ahmed'],
    'Department':['AI','AI','Software','Network','Network']
})

print(df.duplicated())
df = df.drop_duplicates()
df

# Remove duplicates based on only one column
# df.drop_duplicates(subset='Name')

# Remove duplicates based on 2 columns
# df.drop_duplicates(subset=['Name','Department'])

0    False
1     True
2    False
3    False
4     True
dtype: bool

    Name Department
0    Ali         AI
2   Sara   Software
3  Ahmed    Network

In [191]:
df = pd.DataFrame({
    'Department':['AI','AI','Software','Software','Network'],
    'Salary':[60000,65000,50000,52000,47000]
})

print(df.sort_values('Salary', ascending = False))
df.sort_values(['Department', 'Salary'], ascending = [True, False])

  Department  Salary
1         AI   65000
0         AI   60000
3   Software   52000
2   Software   50000
4    Network   47000

  Department  Salary
1         AI   65000
0         AI   60000
4    Network   47000
3   Software   52000
2   Software   50000

### Final Challenge

In [188]:
import numpy as np
employees = pd.DataFrame({
    'Emp_ID':[101,102,103,104,105],
    'Department':['AI','AI','Software','Software','Network'],
    'Salary':[60000,65000,50000,52000,47000]
})

performance = pd.DataFrame({
    'Emp_ID':[101,102,103,104,105],
    'Rating':['A','A','B','C','A']
})

df = employees.merge(performance)
df['Rating'] = df['Rating'].map({'A': 4, 'B': 3, 'C': 2})
deparment_average = df.groupby('Department')['Salary'].transform('mean')
df['High Performer'] = np.where((df['Rating'] >= 4) & (df['Salary'] > deparment_average), 'Yes', 'No')
df

   Emp_ID Department  Salary  Rating High Performer
0     101         AI   60000       4             No
1     102         AI   65000       4            Yes
2     103   Software   50000       3             No
3     104   Software   52000       2             No
4     105    Network   47000       4             No