In [1]:
import pandas as pd

df = pd.DataFrame({
    'Department': [
        'AI', 'AI', 'Software', 'Network',
        'Software', 'AI', 'Network', 'AI'
    ]
})

print(df['Department'].value_counts())
print(df['Department'].value_counts().idxmax())

Department
AI          4
Software    2
Network     2
Name: count, dtype: int64
AI

In [60]:
df = pd.DataFrame({
    'Department': ['AI', 'AI', 'Software', 'Software', 'Network', 'Network'],
    'Salary': [60000, 65000, 50000, 52000, 45000, 47000]
})

df.groupby(['Department'])['Salary'].mean()

Department
AI          62500.0
Network     46000.0
Software    51000.0
Name: Salary, dtype: float64

In [61]:
df.groupby(['Department'])['Salary'].aggregate( Max_Salary='max', Min_Salary ='min', Average_Salary = 'mean')

            Max_Salary  Min_Salary  Average_Salary
Department
AI               65000       60000         62500.0
Network          47000       45000         46000.0
Software         52000       50000         51000.0

In [76]:
df = pd.DataFrame({
    'Department': ['AI','AI','AI','Software','Software','Network'],
    'Gender': ['M','F','M','F','M','F'],
    'Salary': [60000,65000,62000,50000,52000,47000]
})

df.groupby(['Department','Gender'])['Salary'].mean().reset_index()

  Department Gender   Salary
0         AI      F  65000.0
1         AI      M  61000.0
2    Network      F  47000.0
3   Software      F  50000.0
4   Software      M  52000.0

### Mapping

In [149]:
df = pd.DataFrame({
    'Grade': ['A','B','A','C','B']
})

df['Points'] = df['Grade'].map({'A': 4, 'B':3, 'C':2})
df

  Grade  Points
0     A       4
1     B       3
2     A       4
3     C       2
4     B       3

In [ ]:
df = pd.DataFrame({
    'Grade': ['A','B','A','C'],
    'Credit Hours':[3, 4, 4, 2],
}, index=['Course1', 'Course2', 'Course3', 'Course4'])

df['Points'] = df['Grade'].map({'A': 4, 'B':3, 'C':2, 'D':1, 'F':0})
df['Grade Points'] = df['Points']*df['Credit Hours']

gpa = df['Grade Points'].sum()/df['Credit Hours'].sum()
print(df)
print(gpa)

        Grade  Credit Hours  Points  Grade Points
Course1     A             3       4            12
Course2     B             4       3            12
Course3     A             4       4            16
Course4     C             2       2             4
3.3846153846153846

In [163]:
df = pd.DataFrame({
    'Status': ['Pass','Fail','Pass','Pass','Fail']
})

df['Status'] = df['Status'].replace(['Pass','Fail'],[1,0])
df

  Status
0      1
1      0
2      1
3      1
4      0

In [ ]:
df = pd.DataFrame({
    'Department':['AI','AI','Software','Software','Network','Network'],
    'Salary':[60000,65000,50000,52000,45000,47000]
})

df['Above_Average'] = df['Salary'] > df.groupby(['Department'])['Salary'].transform('mean')
df['Above_Average'] = df['Above_Average'].map({True: 'Yes', False: 'No'})
df

# df['Above_Average'] = (df['Salary'].gt(df.groupby('Department')['Salary'].transform('mean')).map({True:'Yes', False:'No'}))

  Department  Salary Above_Average
0         AI   60000            No
1         AI   65000           Yes
2   Software   50000            No
3   Software   52000           Yes
4    Network   45000            No
5    Network   47000           Yes