In [1]:
import pandas as pd

df = pd.DataFrame([['Ali', 20, 'Lahore'], ['Sara', 22, 'Karachi'], ['Ahmed', 21, 'Islamabad']], columns=['Name', 'Age', 'City'])

df

    Name  Age       City
0    Ali   20     Lahore
1   Sara   22    Karachi
2  Ahmed   21  Islamabad

In [2]:
print(df.head(2))
print(df.columns)
print(df.shape)

   Name  Age     City
0   Ali   20   Lahore
1  Sara   22  Karachi
Index(['Name', 'Age', 'City'], dtype='str')
(3, 3)

In [ ]:
print(df['Name'])
print(df[['Name', 'City']])

0      Ali
1     Sara
2    Ahmed
Name: Name, dtype: str
    Name  Age
0    Ali   20
1   Sara   22
2  Ahmed   21

In [21]:
df[(df['Age'] > 20)]

    Name  Age       City
1   Sara   22    Karachi
2  Ahmed   21  Islamabad

In [ ]:
df['Grade'] = ['A','B', 'A']
df

# better practice 
# df = df.assign(Grade=['A','B','A'])

    Name  Age       City Grade
0    Ali   20     Lahore     A
1   Sara   22    Karachi     B
2  Ahmed   21  Islamabad     A