In [2]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Zara', 'Usman'],
    'Age': [20, 22, 21, 23, 19],
    'Marks': [88, 92, 79, 85, 90]
})

print(df.loc[0:2, ['Name', 'Age', 'Marks']])
print(df.iloc[0:3, 0:3])

    Name  Age  Marks
0    Ali   20     88
1   Sara   22     92
2  Ahmed   21     79
    Name  Age  Marks
0    Ali   20     88
1   Sara   22     92
2  Ahmed   21     79

In [32]:
print(df.sort_values('Age', ascending = True))
print('\n')
print(df.sort_values('Marks', ascending = False))

    Name  Age  Marks
4  Usman   19     90
0    Ali   20     88
2  Ahmed   21     79
1   Sara   22     92
3   Zara   23     85


    Name  Age  Marks
1   Sara   22     92
4  Usman   19     90
0    Ali   20     88
3   Zara   23     85
2  Ahmed   21     79

In [33]:
df.loc[df['Age'] > 20, 'Marks'] +=5
df

    Name  Age  Marks
0    Ali   20     88
1   Sara   22     97
2  Ahmed   21     84
3   Zara   23     90
4  Usman   19     90

In [ ]:
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', None, 'Zara'],
    'Age': [20, None, 21, 23]()
})
print(df.isna().sum())
df['Name'] = df['Name'].fillna('Unknown')
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

Name    1
Age     1
dtype: int64

      Name        Age
0      Ali  20.000000
1     Sara  21.333333
2  Unknown  21.000000
3     Zara  23.000000

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Zara', 'Usman'],
    'Age': [20, 22, 21, 23, 19],
    'Marks': [88, 92, 79, 85, 90]
})

df['Status'] = df['Marks'].apply(lambda x: 'Excellent' if x>=85 else 'Good')
df

    Name  Age  Marks     Status
0    Ali   20     88  Excellent
1   Sara   22     92  Excellent
2  Ahmed   21     79       Good
3   Zara   23     85  Excellent
4  Usman   19     90  Excellent

In [66]:
df['Pass_Fail'] = df['Marks'].apply(lambda x: 'Pass' if x >=50 else 'Fail')
df

    Name  Age  Marks     Status Pass_Fail
0    Ali   20     88  Excellent      Pass
1   Sara   22     92  Excellent      Pass
2  Ahmed   21     79       Good      Pass
3   Zara   23     85  Excellent      Pass
4  Usman   19     90  Excellent      Pass

In [68]:
import numpy as np
df['Grade'] = df['Marks'].apply(lambda x: 'A' if x >= 85 else 'B' if x >= 70 and x<=84 else 'C' if x >= 50 and x<=69 else 'D')
df

    Name  Age  Marks     Status Pass_Fail Grade
0    Ali   20     88  Excellent      Pass     A
1   Sara   22     92  Excellent      Pass     A
2  Ahmed   21     79       Good      Pass     B
3   Zara   23     85  Excellent      Pass     A
4  Usman   19     90  Excellent      Pass     A

In [8]:
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Zara'],
    'Hours_Studied': [2, 5, 1, 6],
    'Marks': [40, 78, 35, 90]
})

df['Performance'] = df.apply(lambda x: 'Excellent' if x['Marks'] >= 80 and x['Hours_Studied'] >= 5 else ('Average' if x['Marks'] >= 50 else 'Poor'), axis=1)
df

    Name  Hours_Studied  Marks Performance
0    Ali              2     40        Poor
1   Sara              5     78     Average
2  Ahmed              1     35        Poor
3   Zara              6     90   Excellent

In [7]:
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Zara', 'Usman'],
    'Age': [20, 22, 21, 23, 19],
    'Marks': [88, 92, 79, 85, 90]
})

df['Scholarship'] = df.apply(lambda x: 'Yes' if x['Marks'] >= 85 and x['Age'] < 22 else 'No', axis = 1)
df

    Name  Age  Marks Scholarship
0    Ali   20     88         Yes
1   Sara   22     92          No
2  Ahmed   21     79          No
3   Zara   23     85          No
4  Usman   19     90         Yes

In [10]:
df = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Ahmed', 'Zara', 'Usman'],
    'Attendance': [95, 80, 60, 45, 88],
    'Marks': [88, 92, 79, 85, 90]
})

df['Status'] = df.apply(lambda x: 'Top Performer' if x['Attendance'] >= 90 and x['Marks'] >= 85 else 'Good' if x['Attendance'] >= 75 else 'At Risk', axis = 1)
df

    Name  Attendance  Marks         Status
0    Ali          95     88  Top Performer
1   Sara          80     92           Good
2  Ahmed          60     79        At Risk
3   Zara          45     85        At Risk
4  Usman          88     90           Good

In [12]:
df['Bonus_Marks'] = df.apply(lambda x: x['Marks']*1.1 if x['Marks'] >= 90 else x['Marks']*1.05 if x['Marks'] >=70 and x['Marks'] <= 89 else x['Marks'], axis = 1)
df

    Name  Attendance  Marks         Status  Bonus_Marks
0    Ali          95     88  Top Performer        92.40
1   Sara          80     92           Good       101.20
2  Ahmed          60     79        At Risk        82.95
3   Zara          45     85        At Risk        89.25
4  Usman          88     90           Good        99.00